# Generated by Django 2.2.7 on 2019-11-26 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	#atomic = False
    #initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='user', max_length=200, unique=True)),
                ('user_pass', models.CharField(default='123456', max_length=100)),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
        migrations.CreateModel(
            name='ListAbstract',
            fields=[
                ('list_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('list_name', models.CharField(default='list1', max_length=200, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.User')),
            ],
            options={
                'ordering': ('list_name',),
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, default='item1', max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('S', 'started'), ('P', 'proceed'), ('D', 'done')], default='S', max_length=2)),
                ('description', models.CharField(blank=True, default='NULL', max_length=200)),
                ('expire_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Date')),
                ('list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.ListAbstract')),
            ],
            options={
                'ordering': ('item',),
            },
        ),
    ]
